CREATE TABLE IF NOT EXISTS clientes_inbound (
    id BIGINT NOT NULL AUTO_INCREMENT,
    contact_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) NOT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    convencional VARCHAR(64) DEFAULT NULL,
    ticket_id VARCHAR(128) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    relacion VARCHAR(64) DEFAULT NULL,
    tipo_canal VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    motivo VARCHAR(255) DEFAULT NULL,
    submotivo VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    payload_json LONGTEXT,
    created_by VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_clientes_inbound_contact_id (contact_id),
    KEY idx_clientes_inbound_identification (identification),
    KEY idx_clientes_inbound_campaign (campaign_id),
    KEY idx_clientes_inbound_menu_item (menu_item_id)
);

CREATE TABLE IF NOT EXISTS gestionfinal_inbound (
    id BIGINT NOT NULL AUTO_INCREMENT,
    contact_id VARCHAR(64) NOT NULL,
    cliente_inbound_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    interaction_id VARCHAR(64) DEFAULT NULL,
    action_order INT NOT NULL DEFAULT 1,
    agent VARCHAR(128) DEFAULT NULL,
    management_result_code VARCHAR(64) DEFAULT NULL,
    result_level1 VARCHAR(255) DEFAULT NULL,
    result_level2 VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    fecha_agendamiento VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    tipo_canal VARCHAR(64) DEFAULT NULL,
    relacion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    convencional VARCHAR(64) DEFAULT NULL,
    ticket_id VARCHAR(128) DEFAULT NULL,
    payload_json LONGTEXT,
    fields_meta_json LONGTEXT,
    PREGUNTA_1 TEXT,
    PREGUNTA_2 TEXT,
    PREGUNTA_3 TEXT,
    PREGUNTA_4 TEXT,
    PREGUNTA_5 TEXT,
    PREGUNTA_6 TEXT,
    PREGUNTA_7 TEXT,
    PREGUNTA_8 TEXT,
    PREGUNTA_9 TEXT,
    PREGUNTA_10 TEXT,
    PREGUNTA_11 TEXT,
    PREGUNTA_12 TEXT,
    PREGUNTA_13 TEXT,
    PREGUNTA_14 TEXT,
    PREGUNTA_15 TEXT,
    PREGUNTA_16 TEXT,
    PREGUNTA_17 TEXT,
    PREGUNTA_18 TEXT,
    PREGUNTA_19 TEXT,
    PREGUNTA_20 TEXT,
    PREGUNTA_21 TEXT,
    PREGUNTA_22 TEXT,
    PREGUNTA_23 TEXT,
    PREGUNTA_24 TEXT,
    PREGUNTA_25 TEXT,
    PREGUNTA_26 TEXT,
    PREGUNTA_27 TEXT,
    PREGUNTA_28 TEXT,
    PREGUNTA_29 TEXT,
    PREGUNTA_30 TEXT,
    RESPUESTA_1 TEXT,
    RESPUESTA_2 TEXT,
    RESPUESTA_3 TEXT,
    RESPUESTA_4 TEXT,
    RESPUESTA_5 TEXT,
    RESPUESTA_6 TEXT,
    RESPUESTA_7 TEXT,
    RESPUESTA_8 TEXT,
    RESPUESTA_9 TEXT,
    RESPUESTA_10 TEXT,
    RESPUESTA_11 TEXT,
    RESPUESTA_12 TEXT,
    RESPUESTA_13 TEXT,
    RESPUESTA_14 TEXT,
    RESPUESTA_15 TEXT,
    RESPUESTA_16 TEXT,
    RESPUESTA_17 TEXT,
    RESPUESTA_18 TEXT,
    RESPUESTA_19 TEXT,
    RESPUESTA_20 TEXT,
    RESPUESTA_21 TEXT,
    RESPUESTA_22 TEXT,
    RESPUESTA_23 TEXT,
    RESPUESTA_24 TEXT,
    RESPUESTA_25 TEXT,
    RESPUESTA_26 TEXT,
    RESPUESTA_27 TEXT,
    RESPUESTA_28 TEXT,
    RESPUESTA_29 TEXT,
    RESPUESTA_30 TEXT,
    started_management DATETIME NOT NULL,
    tmstmp DATETIME NOT NULL,
    intentos INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_gestionfinal_inbound_interaction_action (interaction_id, action_order),
    KEY idx_gestionfinal_inbound_identification (identification),
    KEY idx_gestionfinal_inbound_campaign (campaign_id),
    KEY idx_gestionfinal_inbound_contact_id (contact_id),
    CONSTRAINT fk_gestionfinal_inbound_cliente
        FOREIGN KEY (cliente_inbound_id) REFERENCES clientes_inbound(id)
);

CREATE TABLE IF NOT EXISTS gestionhistorica_inbound (
    id BIGINT NOT NULL AUTO_INCREMENT,
    gestionfinal_inbound_id BIGINT DEFAULT NULL,
    contact_id VARCHAR(64) NOT NULL,
    cliente_inbound_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    interaction_id VARCHAR(64) DEFAULT NULL,
    action_order INT NOT NULL DEFAULT 1,
    agent VARCHAR(128) DEFAULT NULL,
    management_result_code VARCHAR(64) DEFAULT NULL,
    result_level1 VARCHAR(255) DEFAULT NULL,
    result_level2 VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    fecha_agendamiento VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    tipo_canal VARCHAR(64) DEFAULT NULL,
    relacion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    convencional VARCHAR(64) DEFAULT NULL,
    ticket_id VARCHAR(128) DEFAULT NULL,
    payload_json LONGTEXT,
    fields_meta_json LONGTEXT,
    PREGUNTA_1 TEXT,
    PREGUNTA_2 TEXT,
    PREGUNTA_3 TEXT,
    PREGUNTA_4 TEXT,
    PREGUNTA_5 TEXT,
    PREGUNTA_6 TEXT,
    PREGUNTA_7 TEXT,
    PREGUNTA_8 TEXT,
    PREGUNTA_9 TEXT,
    PREGUNTA_10 TEXT,
    PREGUNTA_11 TEXT,
    PREGUNTA_12 TEXT,
    PREGUNTA_13 TEXT,
    PREGUNTA_14 TEXT,
    PREGUNTA_15 TEXT,
    PREGUNTA_16 TEXT,
    PREGUNTA_17 TEXT,
    PREGUNTA_18 TEXT,
    PREGUNTA_19 TEXT,
    PREGUNTA_20 TEXT,
    PREGUNTA_21 TEXT,
    PREGUNTA_22 TEXT,
    PREGUNTA_23 TEXT,
    PREGUNTA_24 TEXT,
    PREGUNTA_25 TEXT,
    PREGUNTA_26 TEXT,
    PREGUNTA_27 TEXT,
    PREGUNTA_28 TEXT,
    PREGUNTA_29 TEXT,
    PREGUNTA_30 TEXT,
    RESPUESTA_1 TEXT,
    RESPUESTA_2 TEXT,
    RESPUESTA_3 TEXT,
    RESPUESTA_4 TEXT,
    RESPUESTA_5 TEXT,
    RESPUESTA_6 TEXT,
    RESPUESTA_7 TEXT,
    RESPUESTA_8 TEXT,
    RESPUESTA_9 TEXT,
    RESPUESTA_10 TEXT,
    RESPUESTA_11 TEXT,
    RESPUESTA_12 TEXT,
    RESPUESTA_13 TEXT,
    RESPUESTA_14 TEXT,
    RESPUESTA_15 TEXT,
    RESPUESTA_16 TEXT,
    RESPUESTA_17 TEXT,
    RESPUESTA_18 TEXT,
    RESPUESTA_19 TEXT,
    RESPUESTA_20 TEXT,
    RESPUESTA_21 TEXT,
    RESPUESTA_22 TEXT,
    RESPUESTA_23 TEXT,
    RESPUESTA_24 TEXT,
    RESPUESTA_25 TEXT,
    RESPUESTA_26 TEXT,
    RESPUESTA_27 TEXT,
    RESPUESTA_28 TEXT,
    RESPUESTA_29 TEXT,
    RESPUESTA_30 TEXT,
    started_management DATETIME NOT NULL,
    tmstmp DATETIME NOT NULL,
    intentos INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_gestionhistorica_inbound_contact_id (contact_id),
    KEY idx_gestionhistorica_inbound_identification (identification),
    KEY idx_gestionhistorica_inbound_campaign (campaign_id)
);

CREATE TABLE IF NOT EXISTS gestionfinal_inbound_imagenes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    gestionfinal_inbound_id BIGINT DEFAULT NULL,
    interaction_id VARCHAR(64) NOT NULL,
    contact_id VARCHAR(64) NOT NULL,
    cliente_inbound_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    uploaded_by VARCHAR(128) DEFAULT NULL,
    etiqueta_personalizada VARCHAR(255) DEFAULT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(128) DEFAULT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_gestionfinal_inbound_imagenes_interaction (interaction_id),
    KEY idx_gestionfinal_inbound_imagenes_contact (contact_id),
    KEY idx_gestionfinal_inbound_imagenes_cliente (cliente_inbound_id),
    CONSTRAINT fk_gestionfinal_inbound_imagenes_gestion
        FOREIGN KEY (gestionfinal_inbound_id) REFERENCES gestionfinal_inbound(id),
    CONSTRAINT fk_gestionfinal_inbound_imagenes_cliente
        FOREIGN KEY (cliente_inbound_id) REFERENCES clientes_inbound(id)
);

