CREATE TABLE IF NOT EXISTS clientes_inbound (
    id BIGINT NOT NULL AUTO_INCREMENT,
    contact_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) NOT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    convencional VARCHAR(64) DEFAULT NULL,
    ticket_id VARCHAR(128) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    relacion VARCHAR(64) DEFAULT NULL,
    tipo_canal VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    motivo VARCHAR(255) DEFAULT NULL,
    submotivo VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    payload_json LONGTEXT,
    created_by VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_clientes_inbound_contact_id (contact_id),
    KEY idx_clientes_inbound_identification (identification),
    KEY idx_clientes_inbound_campaign (campaign_id),
    KEY idx_clientes_inbound_menu_item (menu_item_id)
);

CREATE TABLE IF NOT EXISTS gestionfinal_inbound (
    id BIGINT NOT NULL AUTO_INCREMENT,
    contact_id VARCHAR(64) NOT NULL,
    cliente_inbound_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    interaction_id VARCHAR(64) DEFAULT NULL,
    agent VARCHAR(128) DEFAULT NULL,
    management_result_code VARCHAR(64) DEFAULT NULL,
    result_level1 VARCHAR(255) DEFAULT NULL,
    result_level2 VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    fecha_agendamiento VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    tipo_canal VARCHAR(64) DEFAULT NULL,
    relacion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    payload_json LONGTEXT,
    fields_meta_json LONGTEXT,
    started_management DATETIME NOT NULL,
    tmstmp DATETIME NOT NULL,
    intentos INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_gestionfinal_inbound_contact_id (contact_id),
    KEY idx_gestionfinal_inbound_identification (identification),
    KEY idx_gestionfinal_inbound_campaign (campaign_id),
    CONSTRAINT fk_gestionfinal_inbound_cliente
        FOREIGN KEY (cliente_inbound_id) REFERENCES clientes_inbound(id)
);

CREATE TABLE IF NOT EXISTS gestionhistorica_inbound (
    id BIGINT NOT NULL AUTO_INCREMENT,
    gestionfinal_inbound_id BIGINT DEFAULT NULL,
    contact_id VARCHAR(64) NOT NULL,
    cliente_inbound_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    interaction_id VARCHAR(64) DEFAULT NULL,
    agent VARCHAR(128) DEFAULT NULL,
    management_result_code VARCHAR(64) DEFAULT NULL,
    result_level1 VARCHAR(255) DEFAULT NULL,
    result_level2 VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    fecha_agendamiento VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    tipo_canal VARCHAR(64) DEFAULT NULL,
    relacion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    payload_json LONGTEXT,
    fields_meta_json LONGTEXT,
    started_management DATETIME NOT NULL,
    tmstmp DATETIME NOT NULL,
    intentos INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_gestionhistorica_inbound_contact_id (contact_id),
    KEY idx_gestionhistorica_inbound_identification (identification),
    KEY idx_gestionhistorica_inbound_campaign (campaign_id)
);
