CREATE TABLE IF NOT EXISTS clientes_redes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    contact_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    identification VARCHAR(64) NOT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    cantidad_mensajes VARCHAR(64) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_red_social VARCHAR(64) DEFAULT NULL,
    estado_conversacion VARCHAR(128) DEFAULT NULL,
    fecha_gestion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    level1 VARCHAR(255) DEFAULT NULL,
    level2 VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    payload_json LONGTEXT,
    created_by VARCHAR(128) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_clientes_redes_contact_id (contact_id),
    KEY idx_clientes_redes_identification (identification),
    KEY idx_clientes_redes_campaign (campaign_id),
    KEY idx_clientes_redes_menu_item (menu_item_id)
);

CREATE TABLE IF NOT EXISTS gestion_redes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    contact_id VARCHAR(64) NOT NULL,
    cliente_redes_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    interaction_id VARCHAR(64) DEFAULT NULL,
    action_order INT NOT NULL DEFAULT 1,
    agent VARCHAR(128) DEFAULT NULL,
    management_result_code VARCHAR(64) DEFAULT NULL,
    result_level1 VARCHAR(255) DEFAULT NULL,
    result_level2 VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    level1 VARCHAR(255) DEFAULT NULL,
    level2 VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    identification VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_red_social VARCHAR(64) DEFAULT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    estado_conversacion VARCHAR(128) DEFAULT NULL,
    fecha_gestion VARCHAR(64) DEFAULT NULL,
    cantidad_mensajes VARCHAR(64) DEFAULT NULL,
    payload_json LONGTEXT,
    fields_meta_json LONGTEXT,
    started_management DATETIME NOT NULL,
    tmstmp DATETIME NOT NULL,
    intentos INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_gestion_redes_interaction_action (interaction_id, action_order),
    KEY idx_gestion_redes_identification (identification),
    KEY idx_gestion_redes_campaign (campaign_id),
    KEY idx_gestion_redes_contact_id (contact_id),
    CONSTRAINT fk_gestion_redes_cliente
        FOREIGN KEY (cliente_redes_id) REFERENCES clientes_redes(id)
);

CREATE TABLE IF NOT EXISTS gestionhistorica_redes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    gestion_redes_id BIGINT DEFAULT NULL,
    contact_id VARCHAR(64) NOT NULL,
    cliente_redes_id BIGINT NOT NULL,
    campaign_id VARCHAR(255) NOT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    menu_item_id VARCHAR(64) DEFAULT NULL,
    interaction_id VARCHAR(64) DEFAULT NULL,
    action_order INT NOT NULL DEFAULT 1,
    agent VARCHAR(128) DEFAULT NULL,
    management_result_code VARCHAR(64) DEFAULT NULL,
    result_level1 VARCHAR(255) DEFAULT NULL,
    result_level2 VARCHAR(255) DEFAULT NULL,
    categorizacion VARCHAR(255) DEFAULT NULL,
    level1 VARCHAR(255) DEFAULT NULL,
    level2 VARCHAR(255) DEFAULT NULL,
    observaciones TEXT,
    identification VARCHAR(64) DEFAULT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    tipo_cliente VARCHAR(64) DEFAULT NULL,
    tipo_red_social VARCHAR(64) DEFAULT NULL,
    tipo_identificacion VARCHAR(64) DEFAULT NULL,
    nombre_cliente_ref VARCHAR(255) DEFAULT NULL,
    estado_conversacion VARCHAR(128) DEFAULT NULL,
    fecha_gestion VARCHAR(64) DEFAULT NULL,
    cantidad_mensajes VARCHAR(64) DEFAULT NULL,
    payload_json LONGTEXT,
    fields_meta_json LONGTEXT,
    started_management DATETIME NOT NULL,
    tmstmp DATETIME NOT NULL,
    intentos INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_gestionhistorica_redes_contact_id (contact_id),
    KEY idx_gestionhistorica_redes_identification (identification),
    KEY idx_gestionhistorica_redes_campaign (campaign_id)
);
