CREATE TABLE IF NOT EXISTS external_leads (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_channel VARCHAR(32) NOT NULL,
    source_provider VARCHAR(64) NOT NULL DEFAULT 'maquita',
    source_external_id VARCHAR(128) DEFAULT NULL,
    source_import_batch VARCHAR(128) DEFAULT NULL,
    source_sheet_name VARCHAR(64) DEFAULT NULL,
    source_row_number INT DEFAULT NULL,
    fecha_origen_raw VARCHAR(64) DEFAULT NULL,
    fecha_origen_dt DATETIME DEFAULT NULL,
    identification VARCHAR(64) NOT NULL,
    full_name VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    telefono_domicilio VARCHAR(64) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    province VARCHAR(255) DEFAULT NULL,
    estado_civil VARCHAR(128) DEFAULT NULL,
    actividad_economica VARCHAR(255) DEFAULT NULL,
    monto_solicitado VARCHAR(64) DEFAULT NULL,
    monto_aplica VARCHAR(64) DEFAULT NULL,
    autoriza_buro VARCHAR(16) DEFAULT NULL,
    destino_credito TEXT,
    ingreso_neto_recibir VARCHAR(64) DEFAULT NULL,
    tipo_relacion_laboral VARCHAR(128) DEFAULT NULL,
    tipo_vivienda VARCHAR(128) DEFAULT NULL,
    mantiene_hijos VARCHAR(128) DEFAULT NULL,
    otros_ingresos TEXT,
    producto VARCHAR(255) DEFAULT NULL,
    observacion_cooperativa TEXT,
    external_status VARCHAR(255) DEFAULT NULL,
    external_substatus VARCHAR(255) DEFAULT NULL,
    observacion_externo TEXT,
    proceso_a_realizar TEXT,
    fecha_contacto_raw VARCHAR(64) DEFAULT NULL,
    fecha_contacto_dt DATETIME DEFAULT NULL,
    estatus VARCHAR(255) DEFAULT NULL,
    agencia VARCHAR(255) DEFAULT NULL,
    asesor_operativo VARCHAR(255) DEFAULT NULL,
    asesor_externo VARCHAR(255) DEFAULT NULL,
    usuario_maquita VARCHAR(255) DEFAULT NULL,
    seguimiento_kimobill TEXT,
    usuario_asesor_call_center VARCHAR(255) DEFAULT NULL,
    workflow_status VARCHAR(64) NOT NULL DEFAULT 'nuevo',
    workflow_substatus VARCHAR(255) DEFAULT NULL,
    assigned_to VARCHAR(128) DEFAULT NULL,
    assigned_at DATETIME DEFAULT NULL,
    is_ready_for_promotion TINYINT(1) NOT NULL DEFAULT 0,
    promotion_status VARCHAR(64) NOT NULL DEFAULT 'pendiente',
    promoted_at DATETIME DEFAULT NULL,
    promoted_by VARCHAR(128) DEFAULT NULL,
    promotion_notes TEXT,
    payload_json LONGTEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_external_leads_channel_identification (
        source_channel,
        identification
    ),
    KEY idx_external_leads_identification (identification),
    KEY idx_external_leads_workflow_status (workflow_status),
    KEY idx_external_leads_promotion_status (promotion_status),
    KEY idx_external_leads_assigned_to (assigned_to),
    KEY idx_external_leads_assigned_at (assigned_at)
);

CREATE TABLE IF NOT EXISTS external_leads_mail_staging (
    id BIGINT NOT NULL AUTO_INCREMENT,
    import_batch VARCHAR(128) DEFAULT NULL,
    source_sheet_name VARCHAR(64) NOT NULL DEFAULT 'mail',
    row_number INT DEFAULT NULL,
    fecha VARCHAR(64) DEFAULT NULL,
    nombres_completos VARCHAR(255) DEFAULT NULL,
    provincia VARCHAR(255) DEFAULT NULL,
    numero_cedula VARCHAR(64) DEFAULT NULL,
    estado_civil VARCHAR(128) DEFAULT NULL,
    actividad_economica VARCHAR(255) DEFAULT NULL,
    telefono_domicilio VARCHAR(64) DEFAULT NULL,
    telefono_celular VARCHAR(64) DEFAULT NULL,
    monto_solicitado VARCHAR(64) DEFAULT NULL,
    estado VARCHAR(255) DEFAULT NULL,
    sub_estado VARCHAR(255) DEFAULT NULL,
    observacion TEXT,
    proceso_a_realizar TEXT,
    monto_aplica VARCHAR(64) DEFAULT NULL,
    observacion_cooperativa TEXT,
    fecha_contacto VARCHAR(64) DEFAULT NULL,
    estatus VARCHAR(255) DEFAULT NULL,
    agencia VARCHAR(255) DEFAULT NULL,
    asesor_operativo VARCHAR(255) DEFAULT NULL,
    raw_payload_json LONGTEXT,
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_external_leads_mail_staging_batch (import_batch),
    KEY idx_external_leads_mail_staging_identification (numero_cedula)
);

CREATE TABLE IF NOT EXISTS external_leads_rrss_staging (
    id BIGINT NOT NULL AUTO_INCREMENT,
    import_batch VARCHAR(128) DEFAULT NULL,
    source_sheet_name VARCHAR(64) NOT NULL DEFAULT 'rrss',
    row_number INT DEFAULT NULL,
    asesor VARCHAR(255) DEFAULT NULL,
    fecha VARCHAR(64) DEFAULT NULL,
    autoriza_buro VARCHAR(16) DEFAULT NULL,
    numero_cedula VARCHAR(64) DEFAULT NULL,
    apellidos_nombres_completos VARCHAR(255) DEFAULT NULL,
    estado_civil VARCHAR(128) DEFAULT NULL,
    ciudad VARCHAR(255) DEFAULT NULL,
    celular VARCHAR(64) DEFAULT NULL,
    monto_solicitado VARCHAR(64) DEFAULT NULL,
    destino_credito TEXT,
    ingreso_neto_recibir VARCHAR(64) DEFAULT NULL,
    tipo_relacion_laboral VARCHAR(128) DEFAULT NULL,
    actividad_economica_tiempo TEXT,
    tipo_vivienda VARCHAR(128) DEFAULT NULL,
    mantiene_hijos VARCHAR(128) DEFAULT NULL,
    otros_ingresos TEXT,
    producto VARCHAR(255) DEFAULT NULL,
    observacion_agente_maquita TEXT,
    proceso_a_realizar TEXT,
    usuario_maquita VARCHAR(255) DEFAULT NULL,
    estado VARCHAR(255) DEFAULT NULL,
    sub_estado VARCHAR(255) DEFAULT NULL,
    seguimiento_kimobill TEXT,
    usuario_asesor_call_center VARCHAR(255) DEFAULT NULL,
    raw_payload_json LONGTEXT,
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_external_leads_rrss_staging_batch (import_batch),
    KEY idx_external_leads_rrss_staging_identification (numero_cedula)
);
