CREATE TABLE IF NOT EXISTS inbound_no_registradas_asignaciones (
    id BIGINT NOT NULL AUTO_INCREMENT,
    cdr_uniqueid VARCHAR(120) DEFAULT NULL,
    recordingfile VARCHAR(512) DEFAULT NULL,
    recordingfile_normalized VARCHAR(255) DEFAULT NULL,
    management_date_time DATETIME DEFAULT NULL,
    assigned_agent_user_id BIGINT DEFAULT NULL,
    assigned_agent_name VARCHAR(255) NOT NULL,
    assigned_agent_zoiper VARCHAR(20) DEFAULT NULL,
    notes VARCHAR(500) DEFAULT NULL,
    assigned_by_user_id BIGINT DEFAULT NULL,
    assigned_by_username VARCHAR(255) DEFAULT NULL,
    assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_inbound_no_reg_cdr_uniqueid (cdr_uniqueid),
    UNIQUE KEY uq_inbound_no_reg_recording_norm (recordingfile_normalized),
    KEY idx_inbound_no_reg_management_date_time (management_date_time),
    KEY idx_inbound_no_reg_assigned_agent_user (assigned_agent_user_id),
    KEY idx_inbound_no_reg_assigned_agent (assigned_agent_name),
    KEY idx_inbound_no_reg_assigned_at (assigned_at)
);
