CREATE TABLE IF NOT EXISTS tthh_catalog_options (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    catalog_type VARCHAR(64) NOT NULL,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(120) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tthh_catalog_type_code (catalog_type, code),
    KEY idx_tthh_catalog_type_active (catalog_type, is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tthh_employee_profiles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    photo_url VARCHAR(255) NULL,
    national_id VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    marital_status_id BIGINT UNSIGNED NULL,
    children_count INT NOT NULL DEFAULT 0,
    personal_phone VARCHAR(32) NULL,
    alt_phone VARCHAR(32) NULL,
    corporate_email VARCHAR(180) NULL,
    personal_email VARCHAR(180) NULL,
    address_text VARCHAR(255) NULL,
    province VARCHAR(120) NULL,
    sector_id BIGINT UNSIGNED NULL,
    gender_id BIGINT UNSIGNED NULL,
    family_dependents_count INT NOT NULL DEFAULT 0,
    job_title_id BIGINT UNSIGNED NULL,
    department_id BIGINT UNSIGNED NULL,
    area_id BIGINT UNSIGNED NULL,
    hire_date DATE NOT NULL,
    exit_date DATE NULL,
    contract_type_id BIGINT UNSIGNED NULL,
    workday_type_id BIGINT UNSIGNED NULL,
    education_level_id BIGINT UNSIGNED NULL,
    base_salary DECIMAL(12, 2) NOT NULL DEFAULT 0,
    bank_id BIGINT UNSIGNED NULL,
    bank_account_number VARCHAR(64) NULL,
    work_modality_id BIGINT UNSIGNED NULL,
    employee_status_id BIGINT UNSIGNED NULL,
    decimals_accumulation TINYINT(1) NOT NULL DEFAULT 0,
    exit_reason_id BIGINT UNSIGNED NULL,
    emergency_contact_name VARCHAR(180) NULL,
    emergency_contact_relationship VARCHAR(120) NULL,
    emergency_contact_phone VARCHAR(32) NULL,
    med_allergy_drug TINYINT(1) NOT NULL DEFAULT 0,
    med_allergy_food TINYINT(1) NOT NULL DEFAULT 0,
    med_allergy_detail TEXT NULL,
    observations TEXT NULL,
    created_by VARCHAR(120) NULL,
    updated_by VARCHAR(120) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tthh_employee_national_id (national_id),
    UNIQUE KEY uq_tthh_employee_corporate_email (corporate_email),
    KEY idx_tthh_employee_full_name (full_name),
    KEY idx_tthh_employee_status (employee_status_id),
    KEY idx_tthh_employee_department (department_id),
    CONSTRAINT fk_tthh_employee_marital_status FOREIGN KEY (marital_status_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_sector FOREIGN KEY (sector_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_gender FOREIGN KEY (gender_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_job_title FOREIGN KEY (job_title_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_department FOREIGN KEY (department_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_area FOREIGN KEY (area_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_contract_type FOREIGN KEY (contract_type_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_workday_type FOREIGN KEY (workday_type_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_education_level FOREIGN KEY (education_level_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_bank FOREIGN KEY (bank_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_work_modality FOREIGN KEY (work_modality_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_status_catalog FOREIGN KEY (employee_status_id) REFERENCES tthh_catalog_options(id),
    CONSTRAINT fk_tthh_employee_exit_reason FOREIGN KEY (exit_reason_id) REFERENCES tthh_catalog_options(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tthh_catalog_options (catalog_type, code, label, sort_order)
VALUES
    ('marital_status', 'soltero', 'Soltero', 10),
    ('marital_status', 'casado', 'Casado', 20),
    ('sector', 'sur', 'Sur', 10),
    ('sector', 'centro', 'Centro', 20),
    ('sector', 'norte', 'Norte', 30),
    ('sector', 'valles', 'Valles', 40),
    ('gender', 'masculino', 'Masculino', 10),
    ('gender', 'femenino', 'Femenino', 20),
    ('job_title', 'callcenter-comercial', 'Callcenter - Comercial', 10),
    ('job_title', 'marketing', 'Marketing', 20),
    ('job_title', 'analista-calidad', 'Analista Calidad', 30),
    ('job_title', 'supervision', 'Supervision', 40),
    ('job_title', 'analista-th', 'Analista de TH', 50),
    ('job_title', 'ti', 'TI', 60),
    ('job_title', 'gerente-operaciones', 'Gerente de Operaciones', 70),
    ('job_title', 'gerente-comercial', 'Gerente Comercial', 80),
    ('job_title', 'lider-procesos', 'Lider de Procesos', 90),
    ('department', 'ti', 'TI', 10),
    ('department', 'finanzas', 'Finanzas', 20),
    ('department', 'talento-humano', 'Talento Humano', 30),
    ('department', 'comercial', 'Comercial', 40),
    ('department', 'procesos', 'Procesos', 50),
    ('department', 'marketing', 'Marketing', 60),
    ('department', 'legal', 'Legal', 70),
    ('department', 'calidad', 'Calidad', 80),
    ('department', 'supervision', 'Supervision', 90),
    ('department', 'operaciones', 'Operaciones', 100),
    ('department', 'directivos', 'Directivos', 110),
    ('area', 'administracion', 'Administracion', 10),
    ('area', 'call-center', 'Call Center', 20),
    ('area', 'gerencia', 'Gerencia', 30),
    ('contract_type', 'indefinido', 'Indefinido', 10),
    ('contract_type', 'productivo', 'Productivo', 20),
    ('contract_type', 'servicios', 'Servicios', 30),
    ('workday_type', 'completa', 'Completa', 10),
    ('workday_type', 'parcial', 'Parcial', 20),
    ('education_level', 'bachiller', 'Bachiller', 10),
    ('education_level', 'tecnico', 'Tecnico', 20),
    ('education_level', 'tecnologico', 'Tecnologico', 30),
    ('education_level', 'superior', 'Superior', 40),
    ('education_level', 'postgrado', 'Postgrado', 50),
    ('education_level', 'doctorado', 'Doctorado', 60),
    ('bank', 'banco-loja', 'Banco de Loja', 10),
    ('work_modality', 'presencial', 'Presencial', 10),
    ('work_modality', 'remoto', 'Remoto', 20),
    ('work_modality', 'hibrido', 'Hibrido', 30),
    ('employee_status', 'activo', 'Activo', 10),
    ('employee_status', 'inactivo', 'Inactivo', 20),
    ('exit_reason', 'renuncia-voluntaria', 'Renuncia voluntaria', 10),
    ('exit_reason', 'despido-intempestivo', 'Despido Intempestivo', 20)
ON DUPLICATE KEY UPDATE
    label = VALUES(label),
    sort_order = VALUES(sort_order),
    is_active = 1;
